# Generated by Django 4.0.3 on 2022-03-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_phone_user_mobile_rename_user_type_user_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
