# Generated by Django 4.0.3 on 2022-04-11 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_sensorcategory_sensor_category'),
        ('orderProposal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='sensor',
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='orderProposal.orderrequest')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.category')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='orderProposal.orderrequest')),
            ],
        ),
    ]
