# Generated by Django 4.0.3 on 2022-04-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderProposal', '0002_remove_orderrequest_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='orderProposal.orderrequest'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='orderProposal.orderrequest'),
        ),
    ]
