# Generated by Django 4.0.3 on 2022-04-12 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderProposal', '0004_orderrequest_created_by_orderrequest_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
