# Generated by Django 4.0.3 on 2022-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderProposal', '0005_alter_orderrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
