# Generated by Django 4.0.3 on 2022-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderProposal', '0006_orderrequest_created_at_orderrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
