# Generated by Django 4.0.3 on 2022-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderProposal', '0007_alter_orderrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
